import ActionBar from '../actionbar/ActionBar';
import BaseComponent from './BaseComponent';
import ColorPalette from '../colorpalette/ColorPalette';
import DrawingCanvas from '../drawingcanvas/DrawingCanvas';
import DrawingToolBar from '../sidebars/drawingtoolbar/DrawingToolBar';
import HorizontalRuler from '../rulers/horizontalruler/HorizontalRuler';
import HorizontalScrollBar from '../scrollbars/horizontalscrollbar/HorizontalScrollBar';
import MenuBar from '../menubar/MenuBar';
import StatusBar from '../statusbar/StatusBar';
import ToolBar from '../toolbar/ToolBar';
import VerticalRuler from '../rulers/verticalruler/VerticalRuler';
import VerticalScrollBar from '../scrollbars/verticalscrollbar/VerticalScrollBar';
import ConsoleCanvas from '../consolecanvas/ConsoleCanvas';
import LeftSideBar from '../sidebars/leftsidebar/LeftSideBar';
import TabPane from '../tabpane/TabPane';
import ParserContainer from '../ParserContainer';
import ContextMenu from '../contextmenu/ContextMenu';
import IAppContainer from './model/IAppContainer';
import BaseExtension from '../../../../../extension/BaseExtension';
import ExtensionDevelopment from '../../../../../extension/ExtensionDevelopment';
import DrawingToolbarItem from '../sidebars/drawingtoolbar/DrawingToolbarItem';
import { register, registerElement } from '../../../../../customElementRegistration';
import ObjectManagerSelector from '../objectmanagerselector/ObjectManagerSelector';
import IDrawingCanvas from './model/IDrawingCanvas';
import DesignElementTypes from '../../../common/DesignElementTypes';
import DesignElement from '../../../design/base/DesignElement';
declare class AppContainer extends BaseComponent implements IAppContainer {
    private menuBar;
    private toolBar;
    private actionBar;
    private horizontalRuler;
    private verticalRuler;
    private drawingToolBar;
    private drawingCanvas;
    private colorPalette;
    private verticalScrollBar;
    private horizontalScrollBar;
    private statusBar;
    private consolecanvas;
    private leftSideBar;
    private parserContainer;
    private tabPane;
    contextMenu: BaseComponent;
    REI: {
        BaseExtension: typeof BaseExtension;
        ExtensionDevelopment: typeof ExtensionDevelopment;
        ActionBar: typeof ActionBar;
        BaseComponent: typeof BaseComponent;
        ColorPalette: typeof ColorPalette;
        DrawingCanvas: typeof DrawingCanvas;
        DrawingToolBar: typeof DrawingToolBar;
        DrawingToolbarItem: typeof DrawingToolbarItem;
        HorizontalRuler: typeof HorizontalRuler;
        HorizontalScrollBar: typeof HorizontalScrollBar;
        MenuBar: typeof MenuBar;
        ObjectManagerSelector: typeof ObjectManagerSelector;
        StatusBar: typeof StatusBar;
        ToolBar: typeof ToolBar;
        VerticalRuler: typeof VerticalRuler;
        VerticalScrollBar: typeof VerticalScrollBar;
        ConsoleCanvas: typeof ConsoleCanvas;
        LeftSideBar: typeof LeftSideBar;
        TabPane: typeof TabPane;
        ParserContainer: typeof ParserContainer;
        ContextMenu: typeof ContextMenu;
        register: typeof register;
        registerElement: typeof registerElement;
        AppContainer: typeof AppContainer;
        DesignElement: typeof DesignElement;
        DesignElementTypes: typeof DesignElementTypes;
    };
    constructor();
    getMenuBar(): MenuBar;
    getToolBar(): BaseComponent;
    getActionBar(): BaseComponent;
    getHorizontalRuler(): BaseComponent;
    getVerticalRuler(): BaseComponent;
    getDrawingToolBar(): BaseComponent;
    getDrawingCanvas(): IDrawingCanvas;
    getColorPalette(): BaseComponent;
    getVerticalScrollBar(): BaseComponent;
    getHorizontalScrollBar(): BaseComponent;
    getStatusBar(): BaseComponent;
    getConsoleCanvas(): BaseComponent;
    getLeftSideBar(): BaseComponent;
    getParserContainer(): BaseComponent;
    getTabPane(): BaseComponent;
    getContextMenu(): BaseComponent;
}
export default AppContainer;
